## local config
component:
  name: 'project_service_account'
  dependsOn:
    - '../project_service_enable_iam'
    - '../project'

ci:
  mapping:
  - '.' ## current folder relative to where .terrahub.yml is defined
