project:
  name: demo-terraform-automation-gcp
  code: 42c08492
  include:
    - .
  exclude:
    - '**/.terraform/**'
    - '**/node_modules/**'
    - '**/.git/**'
terraform:
  varFile:
    - default.tfvars
  version: 0.11.11
template:
  provider:
    google: {}
  locals:
    google_project_id: terrahub-123456
    google_billing_account: 123456-ABCDEF-ZYXWVU
