project:
  name: demo-terraform-automation-google
  code: 7b3c5d2c
  include:
    - .
  exclude:
    - '**/.terraform/**'
    - '**/node_modules/**'
    - '**/.git/**'
terraform:
  varFile:
    - default.tfvars
template:
  provider:
    google: {}
  locals:
    google_project_id: terrahub-123456
    google_billing_account: 123456-ABCDEF-ZYXWVU
