## project config
project:
  name: demo-terraform-google
  code: f2754a99
  provider: google

## terraform config
terraform:
  varFile:
    - default.tfvars
  var:
    google_org_id: 123456789012
    google_project_id: terrahub-123456
    google_billing_account: 123456-ABCDEF-ZYXWVU
  version: 0.11.7
