component:
  name: google_function
  mapping:
    - .
  dependsOn:
    - ../google_storage
  template:
    resource:
      google_cloudfunctions_function:
        google_function:
          name: 'demofunction${local.project["code"]}'
          depends_on:
            - google_storage_bucket_object.google_storage_object
          region: us-central1
          runtime: nodejs8
          description: My demo function
          available_memory_mb: 128
          source_archive_bucket: '${data.terraform_remote_state.storage.thub_id}'
          source_archive_object: '${google_storage_bucket_object.google_storage_object.name}'
          trigger_http: true
          timeout: 60
          entry_point: helloGET
      google_storage_bucket_object:
        google_storage_object:
          name: demo.zip
          bucket: '${data.terraform_remote_state.storage.thub_id}'
          source: ./demo.zip
    terraform:
      backend:
        local:
          path: /tmp/.terrahub/local_backend/google_function/terraform.tfstate
    data:
      terraform_remote_state:
        storage:
          backend: local
          config:
            path: /tmp/.terrahub/local_backend/google_storage/terraform.tfstate
    output:
      id:
        value: '${google_cloudfunctions_function.google_function.id}'
      trigger_url:
        value: '${google_cloudfunctions_function.google_function.https_trigger_url}'
build:
  env:
    variables:
      THUB_FUNCTION_ZIP: demo.zip
      THUB_BUILD_PATH: ..
      THUB_FUNCTION_TXT: demo.txt
      THUB_BUILD_OK: true
  phases:
    pre_build:
      commands:
        - 'echo "BUILD: Running pre_build step"'
        - 'if [ ! -e "$THUB_FUNCTION_TXT" ]; then touch "$THUB_FUNCTION_TXT"; fi'
      finally:
        - 'echo "BUILD: pre_build step successful"'
    build:
      commands:
        - 'echo "BUILD: Running build step"'
        - >-
          if [ "$(head -n 1 "$THUB_FUNCTION_TXT")" != "$(stat -c %y
          "${THUB_BUILD_PATH}/index.js")" ]; then zip -j ${THUB_FUNCTION_ZIP}
          ${THUB_BUILD_PATH}/index.js; fi
        - >-
          if [ "$(head -n 1 "$THUB_FUNCTION_TXT")" != "$(stat -c %y
          "${THUB_BUILD_PATH}/index.js")" ]; then terrahub configure -i
          google_function -c
          component.template.resource.google_storage_bucket_object.google_storage_object.name=$(date
          +%s).zip; fi
      finally:
        - 'echo "BUILD: build step successful"'
    post_build:
      commands:
        - 'echo "BUILD: Running post_build step"'
        - >-
          echo $(stat -c %y "${THUB_BUILD_PATH}/index.js") >
          "$THUB_FUNCTION_TXT"
      finally:
        - 'echo "BUILD: post_build step successful"'
