component:
  name: google_function
  mapping:
    - .
  dependsOn:
    - ../google_storage
  template:
    resource:
      google_cloudfunctions_function:
        google_function:
          name: 'demofunction${local.project["code"]}'
          depends_on:
            - google_storage_bucket_object.google_storage_object
          project: '${local.google_project_id}'
          region: us-central1
          runtime: nodejs8
          description: My demo function
          available_memory_mb: 128
          source_archive_bucket: '${data.terraform_remote_state.storage.thub_id}'
          source_archive_object: '${google_storage_bucket_object.google_storage_object.name}'
          trigger_http: true
          timeout: 60
          entry_point: helloGET
      google_storage_bucket_object:
        google_storage_object:
          name: demo.zip
          bucket: '${data.terraform_remote_state.storage.thub_id}'
          source: ./demo.zip
    terraform:
      backend:
        local:
          path: /tmp/.terrahub/local_backend/google_function/terraform.tfstate
    data:
      terraform_remote_state:
        storage:
          backend: local
          config:
            path: /tmp/.terrahub/local_backend/google_storage/terraform.tfstate
    output:
      id:
        value: '${google_cloudfunctions_function.google_function.id}'
      trigger_url:
        value: '${google_cloudfunctions_function.google_function.https_trigger_url}'
build:
  env:
    variables:
      THUB_FUNCTION_ZIP: demo.zip
      THUB_FUNCTION_TXT: demo.txt
      COMPONENT_NAME: google_function
      OBJECT_NAME: google_storage_object
      THUB_BUILD_PATH: ..
      THUB_BUILD_OK: false
      THUB_BUCKET_PATH: 'gs://terrahub_bucket_123456'
      THUB_BUCKET_KEY: deploy/google_function
  phases:
    pre_build:
      commands:
        - 'echo "BUILD: Running pre_build step"'
        - >-
          ./scripts/download.sh $THUB_FUNCTION_TXT
          $THUB_BUCKET_PATH/$THUB_BUCKET_KEY/$THUB_FUNCTION_TXT
        - >-
          ./scripts/download.sh $THUB_FUNCTION_ZIP
          $THUB_BUCKET_PATH/$THUB_BUCKET_KEY/$THUB_FUNCTION_

          terrahub configure -i google_function -c
          build.phases.pre_build.commands[3]=./scripts/compare.sh
    build:
      finally:
        - 'echo "BUILD: build step successful"'
    post_build:
      commands:
        - 'echo "BUILD: Running post_build step"'
        - ./scripts/shasum.sh $THUB_FUNCTION_TXT
        - ./scripts/zip.sh $THUB_FUNCTION_ZIP $THUB_BUILD_PATH/*.js
        - >-
          ./scripts/upload.sh $THUB_FUNCTION_TXT
          $THUB_BUCKET_PATH/$THUB_BUCKET_KEY/$THUB_FUNCTION_TXT
        - >-
          ./scripts/upload.sh $THUB_FUNCTION_ZIP
          $THUB_BUCKET_PATH/$THUB_BUCKET_KEY/$THUB_FUNCTION_ZIP
        - rm -f .terrahub_build.env $THUB_FUNCTION_TXT
      finally:
        - 'echo "BUILD: post_build step successful"'
