## local config
component:
  name: 'project-iam-policy-binding-storage-admin'
  dependsOn:
    - '../project_members'

ci:
  mapping:
  - '.' ## current folder relative to where .terrahub.yml is defined
