component:
  name: google_health_check
  template:
    resource:
      google_compute_http_health_check:
        google_health_check:
          name: health-check
          project: ${local.google_project_id}
          request_path: /
          check_interval_sec: 1
          timeout_sec: 1
    output:
      id:
        value: '${google_compute_http_health_check.google_health_check.id}'
      thub_id:
        value: '${google_compute_http_health_check.google_health_check.id}'
      creation_timestamp:
        value: >-
          ${google_compute_http_health_check.google_health_check.creation_timestamp}
      project:
        value: '${google_compute_http_health_check.google_health_check.project}'
      self_link:
        value: '${google_compute_http_health_check.google_health_check.self_link}'
    terraform:
      backend:
        local:
          path: /tmp/.terrahub/local_backend/google_health_check/terraform.tfstate
