## local config
component:
  name: 'service_account'
  mapping: ['.']
  dependsOn:
    - '../project'
  template:
    resource:
      google_service_account:
          service_account:
            project: ${local.google_project_id}
            account_id: ${local.google_service_account_name}
            display_name: ${var.google_service_account_display_name}
    output:
      email:
          value: ${google_service_account.service_account.email}
      name:
          value: ${google_service_account.service_account.name}
      unique_id:
          value: ${google_service_account.service_account.unique_id}
    provider:
      google: {}
    variable:
      google_service_account_display_name:
          type: string
    tfvars:
      google_service_account_display_name: service_account
