component:
  name: google_backend_bucket
  dependsOn:
    - static_website
  template:
    resource:
      google_compute_backend_bucket:
        google_backend_bucket:
          bucket_name: '${data.terraform_remote_state.storage.thub_id}'
          name: static-asset-backend-bucket
          enable_cdn: true
          project: '${local.google_project_id}'
    dynamic:
      data:
        terraform_remote_state:
          - component: static_website
            name: storage
    output:
      id:
        value: '${google_compute_backend_bucket.google_backend_bucket.id}'
      thub_id:
        value: '${google_compute_backend_bucket.google_backend_bucket.id}'
      creation_timestamp:
        value: >-
          ${google_compute_backend_bucket.google_backend_bucket.creation_timestamp}
      project:
        value: '${google_compute_backend_bucket.google_backend_bucket.project}'
      self_link:
        value: '${google_compute_backend_bucket.google_backend_bucket.self_link}'
    terraform:
      backend:
        local:
          path: /tmp/.terrahub/local_backend/google_backend_bucket/terraform.tfstate
