## local config
component:
  name: 'project-service-account'
  dependsOn:
    - '../project-service-enable-iam'
    - '../project'

ci:
  mapping:
  - '.' ## current folder relative to where .terrahub.yml is defined
