## local config
component:
  name: 'project'
  template:
    resource:
      google_project:
          project:
            auto_create_network: ${var.google_project_auto_create_network}
            billing_account: ${local.google_billing_account}
            folder_id: ${var.google_project_folder_id}
            labels: ${merge(var.default_labels, var.custom_labels)}
            name: ${var.google_project_name}
            org_id: ${local.google_org_id}
            project_id: ${local.google_project_id}
    output:
      number:
          value: ${google_project.project.number}
    variable:
      google_project_name:
          type: string
      google_project_folder_id:
          type: string
      google_project_skip_delete:
          type: string
      google_project_auto_create_network:
          type: string
      custom_labels:
          type: map
      default_labels:
          type: map
    tfvars:
      custom_labels: {}
      default_labels:
        description: managed-by-terrahub
        name: project
        thubcode: f2754a99
        thubenv: default
      google_project_auto_create_network: true
      google_project_folder_id: ""
      google_project_name: project
      google_project_skip_delete: false

ci:
  mapping:
  - '.'
