component:
  name: demo_www
  mapping:
    - .
  template:
    resource:
      google_storage_bucket:
        demo_storage_bucket:
          name: 'demo_www_${local.project["code"]}'
          location: US
          project: '${local.google_project_id}'
          force_destroy: 'true'
          website:
            main_page_suffix: 'index.html'
            not_found_page: '404.html'
          cors:
            response_header: ['*']
            method: ['HEAD', 'GET', 'PUT', 'POST', 'DELETE']
            origin: ['*']
            max_age_seconds: '0'
    terraform:
      backend:
        local:
          path: /tmp/.terrahub/local_backend/demo_www/terraform.tfstate

## build config
build:
  env:
    variables:
      THUB_ENV: 'dev'
      THUB_INDEX_FILE: 'www.txt'
      THUB_S3_PATH: 'gs://demo_www_7b3c5d2c'
      THUB_ROBOTS: '../www/robots.dev.txt'
      THUB_BUILD_PATH: '../www'
      THUB_SOURCE_PATH: '../www'
      THUB_BUILD_OK: 'false'
      THUB_MAX_AGE: '600'
  phases:
    pre_build:
      commands:
        - 'echo "BUILD: Running pre_build step"'
        - './scripts/download.sh $THUB_INDEX_FILE $THUB_S3_PATH/$THUB_INDEX_FILE'
        - './scripts/compare.sh $THUB_INDEX_FILE $THUB_SOURCE_PATH'
    post_build:
      commands:
        - 'echo "BUILD: Running post_build step"'
        - './scripts/shasum.sh $THUB_BUILD_PATH/$THUB_INDEX_FILE'
        - './scripts/upload.sh $THUB_BUILD_PATH $THUB_S3_PATH --cache-control max-age=$THUB_MAX_AGE'
        - 'rm -f .terrahub_build.env $THUB_INDEX_FILE'