component:
  name: iam_object_viewer
  dependsOn:
    - static_website
  template:
    resource:
      google_storage_bucket_iam_member:
        iam_object_viewer:
          role: roles/storage.objectViewer
          bucket: terrahub_123456_website
          member: allUsers
    dynamic:
      data:
        terraform_remote_state:
          - component: static_website
            name: storage
    output:
      etag:
        value: '${google_storage_bucket_iam_member.iam_object_viewer.etag}'
    terraform:
      backend:
        local:
          path: /tmp/.terrahub/local_backend/iam_object_viewer/terraform.tfstate
