component:
  name: demo_function
  mapping:
    - .
  dependsOn:
    - ../demo_storage_bucket
  template:
    resource:
      google_cloudfunctions_function:
        demo_function:
          name: 'demofunction${local.project["code"]}'
          depends_on:
            - google_storage_bucket_object.demo_object
          region: us-central1
          runtime: nodejs8
          description: My demo function
          available_memory_mb: 128
          source_archive_bucket: '${data.terraform_remote_state.storage.thub_id}'
          source_archive_object: '${google_storage_bucket_object.demo_object.name}'
          trigger_http: true
          timeout: 60
          entry_point: helloGET
      google_storage_bucket_object:
        demo_object:
          name: deploy/demo_function/1551778012.zip
          bucket: '${data.terraform_remote_state.storage.thub_id}'
          source: ./demo.zip
    terraform:
      backend:
        local:
          path: /tmp/.terrahub/local_backend/demo_function/terraform.tfstate
    data:
      terraform_remote_state:
        storage:
          backend: local
          config:
            path: /tmp/.terrahub/local_backend/demo_storage_bucket/terraform.tfstate
    output:
      id:
        value: '${google_cloudfunctions_function.demo_function.id}'
      trigger_url:
        value: '${google_cloudfunctions_function.demo_function.https_trigger_url}'
build:
  env:
    variables:
      THUB_FUNCTION_ZIP: demo.zip
      THUB_FUNCTION_TXT: demo.txt
      COMPONENT_NAME: demo_function
      OBJECT_NAME: demo_object
      THUB_BUILD_PATH: ..
      THUB_BUILD_OK: 'false'
      THUB_BUCKET_PATH: 'gs://demo_storage_bucket_7b3c5d2c'
      THUB_BUCKET_KEY: deploy/demo_function
  phases:
    pre_build:
      commands:
        - 'echo "BUILD: Running pre_build step"'
        - >-
          ./scripts/download.sh $THUB_FUNCTION_TXT
          $THUB_BUCKET_PATH/$THUB_BUCKET_KEY/$THUB_FUNCTION_TXT
        - ./scripts/compare.sh $THUB_FUNCTION_TXT $THUB_BUILD_PATH/*.js
      finally:
        - 'echo "BUILD: pre_build step successful"'
    build:
      commands:
        - 'echo "BUILD: Running build step"'
        - ./scripts/build.sh $COMPONENT_NAME $OBJECT_NAME $THUB_BUCKET_KEY/
      finally:
        - 'echo "BUILD: build step successful"'
    post_build:
      commands:
        - 'echo "BUILD: Running post_build step"'
        - ./scripts/shasum.sh $THUB_FUNCTION_TXT
        - ./scripts/zip.sh $THUB_FUNCTION_ZIP $THUB_BUILD_PATH/*.js
        - >-
          ./scripts/upload.sh $THUB_FUNCTION_TXT
          $THUB_BUCKET_PATH/$THUB_BUCKET_KEY/$THUB_FUNCTION_TXT
        - rm -f .terrahub_build.env $THUB_FUNCTION_TXT
      finally:
        - 'echo "BUILD: post_build step successful"'
