## local config
component:
  name: 'project_iam_binding_storage_admin'
  dependsOn:
  - '../project_iam_member'
  template:
    resource:
      google_project_iam_binding:
          project_iam_binding_storage_admin:
            members: ${var.google_project_members}
            project: ${local.google_project_id}
            role: ${var.google_project_role}
    output:
      etag:
          value: ${google_project_iam_binding.project_iam_binding_storage_admin.etag}
    provider:
      google: {}
    variable:
      google_project_role:
          type: string
      google_project_members:
          type: list
    tfvars:
      google_project_members:
        - demo@mail.com
      google_project_role: roles/storage.admin

ci:
  mapping:
  - '.'
