component:
  name: google_forwarding_rule
  dependsOn:
    - target_http_proxy
    - google_external_address
  template:
    resource:
      google_compute_global_forwarding_rule:
        google_forwarding_rule:
          name: demo-frontend
          target: '${data.terraform_remote_state.target_http_proxy.self_link}'
          project: '${local.google_project_id}'
          port_range: 80
          ip_address: '${data.terraform_remote_state.external_address.address}'
    dynamic:
      data:
        terraform_remote_state:
          - component: target_http_proxy
            name: target_http_proxy
          - component: google_external_address
            name: external_address
    terraform:
      backend:
        local:
          path: >-
            /tmp/.terrahub/local_backend/google_forwarding_rule/terraform.tfstate
