## local config
component:
  name: 'project_iam_binding_compute_admin'
  mapping: ['.']
  dependsOn:
    - '../project_iam_member'
  template:
    resource:
      google_project_iam_binding:
          project_iam_binding_compute_admin:
            project: ${local.google_project_id}
            members: ${var.google_project_members}
            role: ${var.google_project_role}
    output:
      etag:
          value: ${google_project_iam_binding.project_iam_binding_compute_admin.etag}
    provider:
      google: {}
    variable:
      google_project_role:
          type: string
      google_project_members:
          type: list
    tfvars:
      google_project_members:
        - demo@gmail.com
      google_project_role: roles/compute.instanceAdmin
